# spring.datasource.url=postgresql://cloud_vendor_info_user:TS9DFuahZbKi5g4ze97o3f6PQ4LT7X0x@dpg-d80d033tqb8s73833adg-a.oregon-postgres.render.com/cloud_vendor_info_ikqd
# spring.datasource.username=cloud_vendor_info_user
# spring.datasource.password=TS9DFuahZbKi5g4ze97o3f6PQ4LT7X0x

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://dpg-d80d033tqb8s73833adg-a.oregon-postgres.render.com:5432/cloud_vendor_info_ikqd
spring.datasource.username=cloud_vendor_info_user
spring.datasource.password=TS9DFuahZbKi5g4ze97o3f6PQ4LT7X0x

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true